# Generated by Django 6.0a1 on 2025-11-13 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_exp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_hp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='estate_bonus_exp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='estate_bonus_hp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_hp',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hp', models.PositiveIntegerField(default=10)),
                ('current_mana', models.PositiveIntegerField(default=10)),
                ('max_hp', models.PositiveIntegerField(default=10)),
                ('max_mana', models.PositiveIntegerField(default=10)),
                ('current_exp', models.PositiveIntegerField(default=0)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('strength', models.PositiveIntegerField(default=1)),
                ('dexterity', models.PositiveIntegerField(default=1)),
                ('intelligence', models.PositiveIntegerField(default=1)),
                ('vigor', models.PositiveIntegerField(default=1)),
                ('unallocated_stat_points', models.PositiveIntegerField(default=0)),
                ('estate_bonus_hp', models.IntegerField(default=0)),
                ('estate_bonus_exp', models.IntegerField(default=0)),
                ('avatar_picture', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
