# Generated by Django 6.0a1 on 2025-11-13 11:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sawmill', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('quarry', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('iron_mine', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('healing_pool', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('training_buddy', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('wood', models.PositiveIntegerField(default=0)),
                ('iron', models.PositiveIntegerField(default=0)),
                ('stone', models.PositiveIntegerField(default=0)),
                ('bonus_hp', models.IntegerField(default=0)),
                ('bonus_exp', models.IntegerField(default=0)),
                ('bonus_wood', models.IntegerField(default=0)),
                ('bonus_iron', models.IntegerField(default=0)),
                ('bonus_stone', models.IntegerField(default=0)),
                ('last_production', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estate',
                'verbose_name_plural': 'Estates',
            },
        ),
    ]
